---
- hosts: 10.13.109.35
  user: root
  vars:
   motd_welcome: 'Welcome to Ansible playboot\n Hi, This is YAML\n'
  tasks:
   - name: sample
     copy:
     dest: /etc/motd
     content: "{{ motd_welcome }}" 
  
