---
- hosts: 10.13.109.35
  user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
- name: Download Tomcat
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.61/bin/apache-tomcat-7.0.61.tar.gz dest=/opt/apache-tomcat-7.0.61.tar.gz
